# Nombre del workflow
name: Deploy estático a GitHub Pages

on:
  # Se ejecuta cuando haces un push a la rama 'main'
  push:
    branches: ["main"]

  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Establece los permisos necesarios para el token de GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un deploy simultáneo
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de construcción
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Habilita el caché para acelerar las instalaciones

      - name: Instalar dependencias
        run: npm ci # Usa ci para instalaciones limpias y reproducibles

      - name: Construir el proyecto (Build)
        run: npm run build # Este comando genera la carpeta 'dist'

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite genera los archivos estáticos en la carpeta 'dist' por defecto
          path: './dist'

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
